version: 1.0.{build}
install:
- git clone https://github.com/HumMan/TorrentUnusedCleaner.git
- nuget restore TorrentUnusedCleaner.sln
build:
  project: TorrentUnusedCleaner.sln
  verbosity: minimal
artifacts:
- path: bin\Debug\
  name: TorrentUnusedCleaner
  type: zip